### ISSUE TITLE
AttributeError: 'Net' object has no attribute 'module'

### ISSUE THREAD

**Issue by pur-suit** [PengtaoJiang/L2G#42]
在运行test_l2g_voc.py文件时出现了这个报错：
validating ... models.resnet38
Weights cannot be loaded:
[]
0it [00:05, ?it/s]
Traceback (most recent call last):
  File "/home/work/Desktop/Projects/xy/L2G/scripts/test_l2g_voc.py", line 123, in <module>
    validate(args)
  File "/home/work/Desktop/Projects/xy/L2G/scripts/test_l2g_voc.py", line 76, in validate
    cam_map = model.module.get_heatmaps()
  File "/home/work/anaconda3/envs/l2g/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'Net' object has no attribute 'module'

Process finished with exit code 1
请问这可能是哪方面的问题呢？

**Comment by pur-suit** [comment]
已解决，将muti_scale参数设置为true即可
